### ISSUE TITLE
Applying ES-RNN to sub hourly data

### ISSUE THREAD

**Issue by dan-r95** [kdgutier/esrnn_torch#13]
Hello,

thanks for making this awesome implementation open-source. :100: 
I know that the M4 competition data only deals with data which is at minimum hourly data.
Is it possible to use the algorithm for minutely data? Im a bit confused right now regarding the config. 
thanks a lot !

**Comment by kdgutier** [comment]
You can use the ESRNN with any frequency the README file gives the example on its use on a Yearly dataset.
Make sure you send the pandas with 'unique_id', 'ds' and 'y' columns.
Since you are using minutely data your will have to be a bit careful on your selection of the seasonalities and the input_size.
