### ISSUE TITLE
target between negative and positive

### ISSUE THREAD

**Issue by ramdhan1989** [kdgutier/esrnn_torch#17]
Hi,
I have data with wide range between huge negative and positive values. each ID has different of range. some of them fall between very wide range and some of them are not. it mentioned that the procedure don't accept negative values. how to configure my data properly in order to fit with this application ? do I need to do min max scaler ? if yes, do I scale individual series or all series ? or do you have other suggestions ?

thank you

**Comment by kdgutier** [comment]
Hi @ramdhan1989, you need to have a preprocessing step, to make the values of your series all positive.
Since this is a multiplicative model, it relies on logarithms that have a volatile behavior when you are very close to zero, what we have done is to shift the values, for the train procedure and then unshift them for final the prediction.
