### ISSUE TITLE
M4 starting dates not defined

### ISSUE THREAD

**Issue by adrienbruno** [kdgutier/esrnn_torch#20]
Hello
I thank you very much for this implementation of ES-RNN in python.  Very good job!!
It seems to me that all the time-series start at the same date 1970/01/01 and not at the StartingDate indicated by M4-info.csv.  This date seems to be hard coded in the m4_data.py file at 114 line. If my issue is correct, I hope it helps.
best regards
Adrien

**Comment by kdgutier** [comment]
You are right, the M4 dataset does not have time stamps for the data since they wanted to keep it unidentifiable during the competition (this is also the case for other datasets like M3). At the moment we decided to hardcode the starting date of the time series just for aesthetic purposes of the outputs, but we are certainly looking to improve on the pandas time stamps.
