### ISSUE TITLE
How to set seasonality

### ISSUE THREAD

**Issue by ramdhan1989** [kdgutier/esrnn_torch#25]
Hi, by default seasonality is set to []. my data is daily data and have multiple seasonality : weekly and every six months. how to put in the model ? would you mind explaining the help function below 
seasonality: int list
  list of seasonalities of the time series
  Hourly [24, 168], Daily [7], Weekly [52], Monthly [12],
  Quarterly [4], Yearly []

why for daily sesonality is 7 , weekly 52, etc ?

thanks

**Comment by kdgutier** [comment]
A very common seasonality for daily data is 7 because there are common patterns that repeat every week. 
Particularly if your data come from human economic activities. 
Of course there are 'natural' seasonalities for daily data like 365, the length of the year, but usually you want to train your model with shorter input_sizes.

Weekly is set to 52 because there are 52 weeks in the year.

**Comment by ramdhan1989** [comment]
Ok got it

thanks a lot
